### PR TITLE
Pull request for review of User interface

### PR DESCRIPTION
**Pull request by aulbytj**
OOP (Object Oriented Programming) Project
In this pull request of User-Interface, the objective was to.
Give a programmatic layout how the game will flow from initialization to end.

### CODE REVIEW

**Review by mosaaleb — CHANGES_REQUESTED** [review]
### Well done @aulbytj @appiersign :clap:

You have done great job describing the flow of your program, but there is still some requirements needs to be handled before moving on.

In this milestone we need to think if every case and how to handle it, it's best described in a [flow chart diagrams](https://en.wikipedia.org/wiki/Flowchart) if you want your work to be more organized. 

We need to add more details:

- [x] game tells which player turn it is
- [x] game asks the player to select from available moves
- [x] game informs player if the selected move is invalid
- [x] game displays board after the player move
- [x] game informs player if a selected move is a winning move
- [x] game informs player if a selected move is a draw move
- [x] game repeats all actions for the next player's move
- [ ] A loop is needed to handle turns, also terminate the loop if the game has ended.

All of this is pseudocode or just comments but think of each scenario and how you will handle it.

**[OPTIONAL]** I would suggest also that you figure out which classes you will be using in your project, during this milestone, also try to use these classes (pseudo-code) in `main.rb`. An example would be if you have `Game` and `Board` and `Player` classes:

```ruby
# handling endgame
game = Game.new
game.start

while game.still_playing?
  # ask current player for his move
 game.set_move(1)
  if game.won?
    # print player winner name
    p "congrats #{game.winner_name}"
  else
     game.keep_playing
  end
end

```
Again this is pseudocode to make sure that you understand the big picture of your program.

Please handle these requirements and submit a new code review.

##### Muhammad Ebeid

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team      
#### Great Job so far, but there are a few more things required. 
### General

* [ ] A loop is needed in this game (recommended is `while` but anything else will do) 
* [ ] Inside loop, you should call actions repeated for each move
* [ ] A loop needs to be terminated at some point (after a winning move or draw to be more specific)
### For example 
```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move
  
  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Nice Progress @aulbytj 
You have made some of the requested changes but we still need to have a loop in this game as suggested by the previous reviewers. Please add that then send it for another review.


### Martin Afani

**Review by mcrd25 — APPROVED** [review]
# Changes Approved! 💪 ⏭️ 

Hi Team!

You guys finally added the game loop! 😅 
You may now move to the next milestone. 🙂 

**UNTO ⏭️**

***If you have any questions, now or in the future, do not hesitate to contact me on social media, email or on slack and I will be glad to chat with you.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

**Comment by aulbytj** [comment]
Can't work without the loop!😁 Thanks

**Pull request merged**
